# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protocol_pb2 as protocol__pb2


class KvStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.obtainId = channel.unary_unary(
                '/KVStore.KvStore/obtainId',
                request_serializer=protocol__pb2.VoidMsg.SerializeToString,
                response_deserializer=protocol__pb2.PayloadMsg.FromString,
                )
        self.findNode = channel.unary_unary(
                '/KVStore.KvStore/findNode',
                request_serializer=protocol__pb2.PayloadMsg.SerializeToString,
                response_deserializer=protocol__pb2.PayloadMsg.FromString,
                )


class KvStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def obtainId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KvStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'obtainId': grpc.unary_unary_rpc_method_handler(
                    servicer.obtainId,
                    request_deserializer=protocol__pb2.VoidMsg.FromString,
                    response_serializer=protocol__pb2.PayloadMsg.SerializeToString,
            ),
            'findNode': grpc.unary_unary_rpc_method_handler(
                    servicer.findNode,
                    request_deserializer=protocol__pb2.PayloadMsg.FromString,
                    response_serializer=protocol__pb2.PayloadMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KVStore.KvStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KvStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def obtainId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore.KvStore/obtainId',
            protocol__pb2.VoidMsg.SerializeToString,
            protocol__pb2.PayloadMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def findNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KVStore.KvStore/findNode',
            protocol__pb2.PayloadMsg.SerializeToString,
            protocol__pb2.PayloadMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
